services:
  neo4j:
    image: neo4j:5
    container_name: graph
    ports:
      - "7474:7474" # Neo4j browser
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/12345678
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - "8501:8501" # Streamlit default port
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=12345678
